-- MySQL Script generated by MySQL Workbench
-- Sun Nov 23 04:03:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestaotreino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestaotreino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestaotreino` DEFAULT CHARACTER SET utf8 ;
USE `gestaotreino` ;

-- -----------------------------------------------------
-- Table `gestaotreino`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaotreino`.`usuario` (
  `usucodigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `idade` INT NOT NULL,
  `peso` DECIMAL(5,2) NOT NULL,
  `altura` DECIMAL(4,2) NOT NULL,
  `metapeso` DECIMAL(5,2) NULL DEFAULT NULL,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`usucodigo`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaotreino`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaotreino`.`treino` (
  `trecodigo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `usucodigo` INT NOT NULL,
  PRIMARY KEY (`trecodigo`),
  INDEX `fk_treino_usuario_idx` (`usucodigo` ASC) VISIBLE,
  CONSTRAINT `fk_treino_usuario`
    FOREIGN KEY (`usucodigo`)
    REFERENCES `gestaotreino`.`usuario` (`usucodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaotreino`.`exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaotreino`.`exercicio` (
  `execodigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `carga` DECIMAL(4,2) NOT NULL,
  `repeticoes` INT NOT NULL,
  `series` INT NOT NULL,
  `trecodigo` INT NOT NULL,
  PRIMARY KEY (`execodigo`),
  INDEX `fk_exercicio_treino1_idx` (`trecodigo` ASC) VISIBLE,
  CONSTRAINT `fk_exercicio_treino1`
    FOREIGN KEY (`trecodigo`)
    REFERENCES `gestaotreino`.`treino` (`trecodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaotreino`.`refeicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaotreino`.`refeicao` (
  `refcodigo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `tipo` ENUM('CAFE_DA_MANHA', 'ALMOCO', 'JANTAR', 'LANCHE', 'PRE_TREINO', 'POS_TREINO') NOT NULL,
  `usucodigo` INT NOT NULL,
  PRIMARY KEY (`refcodigo`),
  INDEX `fk_refeicao_usuario1_idx` (`usucodigo` ASC) VISIBLE,
  CONSTRAINT `fk_refeicao_usuario1`
    FOREIGN KEY (`usucodigo`)
    REFERENCES `gestaotreino`.`usuario` (`usucodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaotreino`.`alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaotreino`.`alimento` (
  `alicodigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `quantidade` DECIMAL(6,2) NOT NULL,
  `calorias` INT NOT NULL,
  `macronutriente` ENUM('CARBOIDRATO', 'PROTEINA', 'GORDURA') NOT NULL,
  `refcodigo` INT NOT NULL,
  PRIMARY KEY (`alicodigo`),
  INDEX `fk_alimento_refeicao1_idx` (`refcodigo` ASC) VISIBLE,
  CONSTRAINT `fk_alimento_refeicao1`
    FOREIGN KEY (`refcodigo`)
    REFERENCES `gestaotreino`.`refeicao` (`refcodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaotreino`.`sono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaotreino`.`sono` (
  `soncodigo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horasdormidas` DECIMAL(4,2) NOT NULL,
  `qualidade` ENUM('PESSIMO', 'RUIM', 'REGULAR', 'BOM', 'OTIMO') NOT NULL,
  `usucodigo` INT NOT NULL,
  PRIMARY KEY (`soncodigo`),
  INDEX `fk_sono_usuario1_idx` (`usucodigo` ASC) VISIBLE,
  CONSTRAINT `fk_sono_usuario1`
    FOREIGN KEY (`usucodigo`)
    REFERENCES `gestaotreino`.`usuario` (`usucodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaotreino`.`alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaotreino`.`alerta` (
  `alecodigo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `tipo` ENUM('SONO', 'TREINO', 'ALIMENTACAO', 'DESEMPENHO') NOT NULL,
  `mensagem` VARCHAR(255) NULL DEFAULT NULL,
  `usucodigo` INT NOT NULL,
  PRIMARY KEY (`alecodigo`),
  INDEX `fk_alerta_usuario1_idx` (`usucodigo` ASC) VISIBLE,
  CONSTRAINT `fk_alerta_usuario1`
    FOREIGN KEY (`usucodigo`)
    REFERENCES `gestaotreino`.`usuario` (`usucodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaotreino`.`desempenho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaotreino`.`desempenho` (
  `descodigo` INT NOT NULL AUTO_INCREMENT,
  `inicioperiodo` DATE NOT NULL,
  `fimperiodo` DATE NOT NULL,
  `mediatreinos` DOUBLE NULL DEFAULT NULL,
  `mediasono` DOUBLE NULL DEFAULT NULL,
  `mediacalorias` DOUBLE NULL DEFAULT NULL,
  `indicedesempenho` DOUBLE NULL DEFAULT NULL,
  `usucodigo` INT NOT NULL,
  PRIMARY KEY (`descodigo`),
  INDEX `fk_desempenho_usuario1_idx` (`usucodigo` ASC) VISIBLE,
  CONSTRAINT `fk_desempenho_usuario1`
    FOREIGN KEY (`usucodigo`)
    REFERENCES `gestaotreino`.`usuario` (`usucodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaotreino`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaotreino`.`relatorio` (
  `relcodigo` INT NOT NULL AUTO_INCREMENT,
  `datainicio` DATE NOT NULL,
  `datafim` DATE NOT NULL,
  `tipo` ENUM('SEMANAL', 'MENSAL', 'PERSONALIZADO') NULL DEFAULT NULL,
  `usucodigo` INT NOT NULL,
  PRIMARY KEY (`relcodigo`),
  INDEX `fk_relatorio_usuario1_idx` (`usucodigo` ASC) VISIBLE,
  CONSTRAINT `fk_relatorio_usuario1`
    FOREIGN KEY (`usucodigo`)
    REFERENCES `gestaotreino`.`usuario` (`usucodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
