/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestaotreinos.view;
import gestaotreinos.controller.entity.RefeicaoController;
import gestaotreinos.controller.entity.SonoController;
import gestaotreinos.controller.entity.TreinoController;
import gestaotreinos.model.dao.UsuarioDAO;
import gestaotreinos.model.dao.ConexaoBD;
import gestaotreinos.model.entity.Refeicao;
import gestaotreinos.model.entity.Sono;
import gestaotreinos.model.entity.Treino;
import gestaotreinos.model.entity.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author gusta
 */
public class ViewHistorico extends javax.swing.JFrame {
    private Usuario usuario;
    private List<Object> listaAtual;
    private String tipoAtual;
    private int idAtual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewHistorico.class.getName());
   
    /**
     * Creates new form ViewHistorico2
     */
    public ViewHistorico(Usuario usuario) {
        this.usuario = usuario;
        this.idAtual =usuario.getIdUsuario();
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCbHistorico = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        voltar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCbHistorico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Treino", "Sono", "Refeição" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        voltar.setText("Voltar");
        voltar.addActionListener(this::voltarActionPerformed);

        excluir.setText("Excluir");
        excluir.addActionListener(this::excluirActionPerformed);

        buscar.setText("Buscar");
        buscar.addActionListener(this::buscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voltar)
                        .addGap(171, 171, 171)
                        .addComponent(buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jCbHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jCbHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(excluir)
                    .addComponent(buscar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void limparTabela() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        listaAtual = new ArrayList<>();
        listaAtual.clear();
    }
    
    private void carregarTreinos() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setColumnIdentifiers(new String[]{"Data", "Tipo", "Qtd. Exercícios"}); 
        TreinoController tCont = new TreinoController();
        List<Treino> listaTreino = tCont.listarHistorico(usuario.getIdUsuario());
        
        if (listaTreino != null) {
            for (Treino t : listaTreino) {
                model.addRow(new Object[]{t.getData(), t.getTipo(), (t.getExercicios() != null ? t.getExercicios().size() : 0)});
                listaAtual.add(t);
            }
        }
    }

    private void carregarSonos() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setColumnIdentifiers(new String[]{"Data", "Horas", "Qualidade"});
        
        SonoController sCont = new SonoController();
        List<Sono> listaSono = sCont.listarHistorico(usuario.getIdUsuario());
        if (listaSono != null) {
            for (Sono s : listaSono) {
                model.addRow(new Object[]{s.getData(), s.getHorasDormidas() + "h", s.getQualidade()});
                listaAtual.add(s);
            }
        }
    }
    private void carregarRefeicoes() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setColumnIdentifiers(new String[]{"Data", "Tipo", "Calorias"});   
        RefeicaoController rCont = new RefeicaoController();
        List<Refeicao> lista = rCont.listarHistorico(usuario.getIdUsuario());
        
        if (lista != null) {
            for (Refeicao r : lista) {
                double cals = r.calcularCalorias(); 
                model.addRow(new Object[]{r.getData(), r.getTipo(), String.format(cals + " kcal")});
                listaAtual.add(r);
            }
        }
    }
    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
       ViewPrincipal oViewPrincipal = new ViewPrincipal(usuario);   
        oViewPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String tipoSelecionado = (String) jCbHistorico.getSelectedItem();
        this.tipoAtual = tipoSelecionado;
        limparTabela();

        try {
            if(tipoAtual.equalsIgnoreCase("Treino")){
                carregarTreinos();
            }else if(tipoAtual.equalsIgnoreCase("Sono")){
                carregarSonos();
            }else if(tipoAtual.equalsIgnoreCase("Refeição")){
                carregarRefeicoes();
            }else{
                JOptionPane.showMessageDialog(this, "Selecione um tipo valido");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }          
    }//GEN-LAST:event_buscarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed

        int linha = jTable1.getSelectedRow();
        Object itemExcluir = listaAtual.get(linha);
        if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um item para excluir");
            return;
        }
        String msg = "Registro excluido.";
        
        try {
            if (itemExcluir instanceof Treino) {
                TreinoController tCont = new TreinoController();
                msg = tCont.excluirTreino(((Treino) itemExcluir).getIdTreino());
            } else if (itemExcluir instanceof Sono) {
                SonoController sCont = new SonoController();
                msg = sCont.excluirSono(((Sono) itemExcluir).getIdSono());
            } else if (itemExcluir instanceof Refeicao) {
                RefeicaoController rCont = new RefeicaoController();
                msg = rCont.excluirRefeicao(((Refeicao) itemExcluir).getIdRefeicao());
            }
            JOptionPane.showMessageDialog(this, msg);
            buscarActionPerformed(null);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewHistorico(usuario).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton excluir;
    private javax.swing.JComboBox<String> jCbHistorico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
