/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package gestaotreinos.view;

import gestaotreinos.model.dao.AlimentoDAO;
import gestaotreinos.model.dao.ConexaoBD;
import gestaotreinos.model.entity.Alimento;
import gestaotreinos.model.entity.Refeicao;
import gestaotreinos.model.entity.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author rafae
 */
public class ViewRegistrarAlimento extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewRegistrarAlimento.class.getName());

    private Refeicao refeicao;
    private Usuario usuario;
    
    /** Creates new form ViewRegistrarAlimento */
    public ViewRegistrarAlimento(Usuario usuario, Refeicao refeicao) {
        initComponents();
        this.refeicao = refeicao;
        this.usuario = usuario;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeAlimento = new javax.swing.JTextField();
        txtCalorias = new javax.swing.JSpinner();
        btnAvancar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar Alimento");

        jLabel2.setText("Nome:");

        jLabel3.setText("Calorias:");

        txtCalorias.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5000, 1));

        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(this::btnAvancarActionPerformed);

        jLabel4.setText("Quantidade:");

        txtQuantidade.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jButton1.setText("Voltar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeAlimento)
                    .addComponent(txtCalorias, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(txtQuantidade))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvancar)
                    .addComponent(jButton1))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        
        Alimento alimento = new Alimento();
        alimento.setNomeAlimento(txtNomeAlimento.getText());
        alimento.setQuantidade((Double) txtQuantidade.getValue());
        alimento.setCalorias((Integer) txtCalorias.getValue());

        alimento.setRefeicao(refeicao);

        AlimentoDAO alimentoDAO = new AlimentoDAO(ConexaoBD.conectaBD());
        alimentoDAO.inserir(alimento);
        
        ViewRegistrarAlimento oViewRegistrarAlimento = new ViewRegistrarAlimento(usuario, refeicao);   
        oViewRegistrarAlimento.setVisible(true);
        dispose();
        
        /*
        String sNomeAlimento = txtNomeAlimento.getText().trim();
        Integer iCalorias = (Integer) txtCalorias.getValue();
        Double dQuantidade = (Double) txtQuantidade.getValue();
        
        Alimento alimento = new Alimento(sNomeAlimento, dQuantidade, iCalorias);
        AlimentoDAO alimentoDAO = new AlimentoDAO(ConexaoBD.conectaBD());
        
        boolean bSucesso = alimentoDAO.inserirAlimento(alimento, );
        
        if (bSucesso) {
            JOptionPane.showMessageDialog(this, "Alimento Inserido com Sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao Inserir Alimento");
        }
        */
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Refeição incluída com Sucesso!");
        ViewPrincipal oViewPrincipal = new ViewPrincipal(usuario);   
        oViewPrincipal.setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new ViewRegistrarAlimento(usuario, refeicao).setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner txtCalorias;
    private javax.swing.JTextField txtNomeAlimento;
    private javax.swing.JSpinner txtQuantidade;
    // End of variables declaration//GEN-END:variables

}
