/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestaotreinos.view;

import gestaotreinos.enums.TipoRefeicao;
import gestaotreinos.model.dao.ConexaoBD;
import gestaotreinos.model.dao.RefeicaoDAO;
import gestaotreinos.model.entity.Refeicao;
import gestaotreinos.model.entity.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author rafae
 */
public class ViewRegistrarRefeicao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewRegistrarRefeicao.class.getName());

    private static Usuario usuario;
    
    /**
     * Creates new form ViewRegistrarRefeicao
     */
    public ViewRegistrarRefeicao(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        preencherComboboxTipo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTipoRefeicao = new javax.swing.JComboBox<>();
        btnAvancar = new javax.swing.JButton();
        txtData = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Refeição");

        jLabel1.setText("Registrar Refeição");

        jLabel3.setText("Data:");

        jLabel4.setText("Tipo:");

        cmbTipoRefeicao.addActionListener(this::cmbTipoRefeicaoActionPerformed);

        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(this::btnAvancarActionPerformed);

        txtData.setDateFormatString("dd/MM/yyyy");

        jButton1.setText("Voltar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipoRefeicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAvancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addComponent(btnAvancar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
    try {
        if (txtData.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma data.");
            return;
        }

        if (cmbTipoRefeicao.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecione o tipo da refeição.");
            return;
        }

        java.util.Date utilDate = txtData.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

        String tipoSelecionado = (String) cmbTipoRefeicao.getSelectedItem().toString();
        //TipoRefeicao tipo = TipoRefeicao.fromLabel(tipoSelecionado); 
        TipoRefeicao tipo = (TipoRefeicao) cmbTipoRefeicao.getSelectedItem();

        Refeicao oRefeicao = new Refeicao();
        oRefeicao.setData(sqlDate);
        oRefeicao.setTipo(tipo);
        oRefeicao.setUsuario(usuario);

        RefeicaoDAO refeicaoDAO = new RefeicaoDAO(ConexaoBD.conectaBD());
        int idRefeicao = refeicaoDAO.inserirRefeicao(oRefeicao);

        if (idRefeicao <= 0) {
            JOptionPane.showMessageDialog(this, "Erro ao registrar refeição.");
            return;
        }

        oRefeicao.setIdRefeicao(idRefeicao);

        ViewRegistrarAlimento telaAlim = new ViewRegistrarAlimento(usuario, oRefeicao);
        telaAlim.setVisible(true);

        this.dispose();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao avançar: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void cmbTipoRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoRefeicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoRefeicaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ViewPrincipal oViewPrincipal = new ViewPrincipal(usuario);
        oViewPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void preencherComboboxTipo() {
        cmbTipoRefeicao.removeAllItems();
        for (TipoRefeicao t : TipoRefeicao.values()) {
            cmbTipoRefeicao.addItem(t);
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewRegistrarRefeicao(usuario).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JComboBox<gestaotreinos.enums.TipoRefeicao> cmbTipoRefeicao;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser txtData;
    // End of variables declaration//GEN-END:variables
}
