/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestaotreinos.view;

import gestaotreinos.enums.TipoRefeicao;
import gestaotreinos.model.dao.ConexaoBD;
import gestaotreinos.model.dao.RefeicaoDAO;
import gestaotreinos.model.entity.Refeicao;
import gestaotreinos.model.entity.Usuario;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author rafae
 */
public class ViewRegistrarRefeicao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewRegistrarRefeicao.class.getName());

    private Usuario usuario;
    
    /**
     * Creates new form ViewRegistrarRefeicao
     */
    public ViewRegistrarRefeicao(Usuario usuario) {
        initComponents();
        cmbTipoRefeicao.setModel(new DefaultComboBoxModel<>(TipoRefeicao.values()));
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTipoRefeicao = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        txtData = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Refeição");

        jLabel1.setText("Registrar Refeição");

        jLabel3.setText("Data:");

        jLabel4.setText("Tipo:");

        cmbTipoRefeicao.addActionListener(this::cmbTipoRefeicaoActionPerformed);

        jButton2.setText("Avançar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        txtData.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTipoRefeicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addComponent(jButton2)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoRefeicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoRefeicaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Date dData = txtData.getDate();
        //java.time.Instant instant = dData.toInstant();
        //LocalDate dDataConvertida = instant.atZone(ZoneId.from(instant).systemDefault()).toLocalDate();
        
        TipoRefeicao sTipo = (TipoRefeicao) cmbTipoRefeicao.getSelectedItem();

        Refeicao refeicao = new Refeicao(usuario, dData, sTipo);
        refeicao.setUsuario(usuario);
        refeicao.setData(dData);
        refeicao.setTipo(sTipo);
        
        RefeicaoDAO refeicaoDAO = new RefeicaoDAO(ConexaoBD.conectaBD());
        refeicao = refeicaoDAO.inserir(refeicao);
        
        ViewRegistrarAlimento oViewRegistrarAlimento = new ViewRegistrarAlimento(usuario);
        oViewRegistrarAlimento.setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<gestaotreinos.enums.TipoRefeicao> cmbTipoRefeicao;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser txtData;
    // End of variables declaration//GEN-END:variables
}
