/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestaotreinos.view;
import gestaotreinos.model.entity.Desempenho;
import gestaotreinos.controller.entity.DesempenhoController;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import gestaotreinos.model.entity.Usuario;

/**
 *
 * @author rafae
 */
public class ViewRelatorio extends javax.swing.JFrame {
    Desempenho desAtual;
    int idUsuario = usuario.getIdUsuario();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewRelatorio.class.getName());

    private static Usuario usuario;
    
    /**
     * Creates new form ViewRelatorio
     */
    public ViewRelatorio(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        pgbSono = new javax.swing.JProgressBar();
        pgbNota = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pgbCalorias = new javax.swing.JLabel();
        btnGerarAnalise = new javax.swing.JButton();
        cbObjetivo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        pgbTreino = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pgbCal = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pgbSono.setMaximum(8);
        pgbSono.setStringPainted(true);

        pgbNota.setMaximum(10);
        pgbNota.setStringPainted(true);

        jLabel1.setText("Treino");

        jLabel2.setText("Sono");

        pgbCalorias.setText("Calorias");

        btnGerarAnalise.setText("Gerar analise");
        btnGerarAnalise.addActionListener(this::btnGerarAnaliseActionPerformed);

        cbObjetivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ganhar Massa", "Perder peso" }));
        cbObjetivo.addActionListener(this::cbObjetivoActionPerformed);

        jLabel3.setText("objetivo:");

        pgbTreino.setMaximum(7);
        pgbTreino.setStringPainted(true);

        jLabel4.setText("Nota");

        jTextA.setColumns(20);
        jTextA.setRows(5);
        jScrollPane1.setViewportView(jTextA);

        jButton1.setText("Voltar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel5.setText("Alertas");

        pgbCal.setMaximum(8);
        pgbCal.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(btnGerarAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21))
                                .addComponent(jLabel3)
                                .addComponent(cbObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(pgbCalorias))
                                .addComponent(pgbCal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pgbTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pgbSono, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(pgbNota, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(148, 148, 148))))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pgbNota, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pgbTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbSono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(pgbCalorias)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbCal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGerarAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarAnaliseActionPerformed
          
       DesempenhoController dCont = new DesempenhoController();
       
       desAtual = dCont.gerarRelatorioSemanal(idUsuario);
       if(this.desAtual != null){
       
       pgbTreino.setMaximum(7);
       pgbTreino.setValue((int) desAtual.getMediaTreino());
       pgbTreino.setString((int) desAtual.getMediaTreino() + " / 7 Treinos");
       definirCor(pgbTreino, (int) desAtual.getMediaTreino(), 3, 5); 
       
       pgbSono.setMaximum(12);
       pgbSono.setValue((int) desAtual.getMediaSono());
       pgbSono.setString((int) desAtual.getMediaSono() + " /h por dia" );
       definirCor(pgbSono, (int) desAtual.getMediaSono(), 6, 8); 
       
       pgbNota.setMaximum(10);
       pgbNota.setValue((int) desAtual.getIndiceDesempenho());
       pgbNota.setString((int) desAtual.getIndiceDesempenho() + " / 10");
       definirCor(pgbNota, (int) desAtual.getIndiceDesempenho(), 3, 5);
       
       jTextA.setText(this.desAtual.getTextoResumo());
       
       atualizarBarraCalorias();
       
       }else{
           JOptionPane.showMessageDialog(this, "erro ao gerar relatorio");
       }
    } 
    
       public void atualizarBarraCalorias(){
            if(this.desAtual == null) {
                return;
            }

            double tmb = desAtual.getUsuario().calcularTMB();
            double medConsumo = desAtual.getMediaCalorias();
            String objetivo = cbObjetivo.getSelectedItem().toString();

            int maxCal = (int) (tmb * 1.5);
            pgbCal.setMaximum(maxCal);
            pgbCal.setValue((int) medConsumo);

            pgbCal.setString(String.format("%.0f / %.0f", medConsumo, tmb));

            if (objetivo.equals("Perder peso")) {
                if (medConsumo > tmb) {
                    pgbCal.setForeground(Color.RED);
                } else if (medConsumo < (tmb * 0.5)) {
                    pgbCal.setForeground(Color.RED);
                } else {
                    pgbCal.setForeground(new Color(0, 153, 0));
                }
            } else if (objetivo.equals("Ganhar Massa")) {
                if (medConsumo < tmb) {
                    pgbCal.setForeground(Color.ORANGE);
                } else if (medConsumo > (tmb * 1.5)) {
                    pgbCal.setForeground(Color.RED);
                } else {
                    pgbCal.setForeground(new Color(0, 153, 0));
                }
            }
    }//GEN-LAST:event_btnGerarAnaliseActionPerformed
    
    private void definirCor(javax.swing.JProgressBar barra, int valor, int minimo, int bom) {
       if (valor >= bom) {
            barra.setForeground(new Color(0, 153, 0));
        } else if (valor >= minimo) {
            barra.setForeground(Color.ORANGE);
        } else {
            barra.setForeground(Color.RED);
        }
    }
    private void cbObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbObjetivoActionPerformed
        atualizarBarraCalorias();
    }//GEN-LAST:event_cbObjetivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ViewRegistros oViewRegistros = new ViewRegistros(usuario);
        oViewRegistros.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */    

       /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewRelatorio(usuario).setVisible(true));

        /* Create and display the form */

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> new ViewRelatorio(usuario).setVisible(true));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarAnalise;
    private javax.swing.JComboBox<String> cbObjetivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextA;
    private javax.swing.JProgressBar pgbCal;
    private javax.swing.JLabel pgbCalorias;
    private javax.swing.JProgressBar pgbNota;
    private javax.swing.JProgressBar pgbSono;
    private javax.swing.JProgressBar pgbTreino;
    // End of variables declaration//GEN-END:variables
}
