/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestaotreinos.view;
import gestaotreinos.controller.entity.TreinoController;
import gestaotreinos.model.entity.Exercicio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author rafae
 */
public class ViewRegistrarExercicios extends javax.swing.JFrame {
    
    String tipoAtual;
    String dataAtual;
    int idAtual = 1;
    
    
    public void mostrarLista(String data, String tipo){
        tipoAtual = tipo;
        dataAtual = data;
        
        limparCampos();
        TreinoController tCont = new TreinoController();
        List<Exercicio> listaExercicios = tCont.gerarExercicios(tipoAtual);
        
        if(listaExercicios != null){
            
            jL1.setText(listaExercicios.get(0).getNome());
            jL2.setText(listaExercicios.get(1).getNome());
            jL3.setText(listaExercicios.get(2).getNome());        
        }else{
            System.out.println("erro: lista e null ou tem menos de 3 exercícios");
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewRegistrarExercicios.class.getName());

    /**
     * Creates new form ViewRegistrarExercicios
     */
    public ViewRegistrarExercicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void limparCampos() {
    jCarga1.setValue(0); jSerie1.setValue(0); jReps1.setValue(0);
    jCarga2.setValue(0); jSerie2.setValue(0); jReps2.setValue(0);
    jCarga3.setValue(0); jSerie3.setValue(0); jReps3.setValue(0);
    
    jL1.setText("-"); jL2.setText("-"); jL3.setText("-");
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jCarga1 = new javax.swing.JSpinner();
        jSerie1 = new javax.swing.JSpinner();
        jReps1 = new javax.swing.JSpinner();
        jCarga2 = new javax.swing.JSpinner();
        jSerie2 = new javax.swing.JSpinner();
        jReps2 = new javax.swing.JSpinner();
        jCarga3 = new javax.swing.JSpinner();
        jSerie3 = new javax.swing.JSpinner();
        jReps3 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar Exercícios");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jL1.setText("jLabel2");

        jL2.setText("jLabel2");

        jL3.setText("jLabel2");

        jCarga1.setModel(new javax.swing.SpinnerNumberModel());

        jSerie1.setModel(new javax.swing.SpinnerNumberModel());

        jReps1.setModel(new javax.swing.SpinnerNumberModel());

        jCarga2.setModel(new javax.swing.SpinnerNumberModel());

        jSerie2.setModel(new javax.swing.SpinnerNumberModel());

        jReps2.setModel(new javax.swing.SpinnerNumberModel());

        jCarga3.setModel(new javax.swing.SpinnerNumberModel());

        jSerie3.setModel(new javax.swing.SpinnerNumberModel());

        jReps3.setModel(new javax.swing.SpinnerNumberModel());

        jLabel2.setText("Carga:");
        jLabel2.setName(""); // NOI18N

        jLabel3.setText("Series: ");

        jLabel4.setText("Repetições: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(226, 226, 226))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1))
                .addGap(218, 218, 218))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL3)
                        .addGap(43, 43, 43)
                        .addComponent(jCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jL2)
                            .addGap(43, 43, 43)
                            .addComponent(jCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jL1)
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSerie1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSerie2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSerie3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jReps1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReps2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReps3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSerie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReps1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSerie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReps2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL3)
                    .addComponent(jCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSerie3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReps3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        jLabel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        List<Exercicio> exercicios = new ArrayList<>();
        
        int carga = (Integer) jCarga1.getValue();
        int series= (Integer) jSerie1.getValue();
        int reps = (Integer) jReps1.getValue();
        
        
        if(carga > 0 || series > 0 || reps > 0){
            Exercicio e1 = new Exercicio();
            e1.setCarga (carga);
            e1.setSeries(series);
            e1.setRepeticoes(reps);
            e1.setNome(jL1.getText());
            exercicios.add(e1);
        }
      
        carga = (Integer) jCarga2.getValue();
        series = (Integer) jSerie2.getValue();
        reps = (Integer) jReps2.getValue();
        
        
        if(carga > 0 || series > 0 || reps > 0){
            Exercicio e2 = new Exercicio();
            e2.setCarga (carga);
            e2.setSeries(series);
            e2.setRepeticoes(reps);
            e2.setNome(jL2.getText());
            exercicios.add(e2);
        }
        carga = (Integer) jCarga3.getValue();
        series = (Integer) jSerie3.getValue();
        reps = (Integer) jReps3.getValue();
        
        
        if(carga > 0 || series > 0 || reps > 0){
            Exercicio e3 = new Exercicio();
            e3.setCarga (carga);
            e3.setSeries(series);
            e3.setRepeticoes(reps);
            e3.setNome(jL3.getText());
            exercicios.add(e3);
        }
        TreinoController tCont = new TreinoController();
        String res = tCont.salvarTreino(dataAtual, tipoAtual, idAtual, exercicios);
        JOptionPane.showMessageDialog(this, res);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewRegistrarExercicios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JSpinner jCarga1;
    private javax.swing.JSpinner jCarga2;
    private javax.swing.JSpinner jCarga3;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jReps1;
    private javax.swing.JSpinner jReps2;
    private javax.swing.JSpinner jReps3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSerie1;
    private javax.swing.JSpinner jSerie2;
    private javax.swing.JSpinner jSerie3;
    // End of variables declaration//GEN-END:variables
}
